services:
  STA:
    image: registry.gitlab.com/samurailink3/sta:latest
    pull_policy: never
    restart: unless-stopped
    environment:
      PORT: 3000
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_ENV: "production"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - STA-DB
  STA-DB:
    image: docker.io/library/postgres:latest
    pull_policy: always
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  postgres-data:
