default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: 'dev-db'
  port: 5432
  database: 'sta-development'
  username: 'sta-development-admin'
  password: 'sta-development-admin'

test:
  <<: *default
  adapter: sqlite3
  database: storage/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: 'sta-postgres'
  port: 5432
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

cable:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] || 'sta-postgres' %>
  port: <%= ENV['POSTGRES_PORT'] || 5432 %>
  database: <%= ENV['POSTGRES_DB'] || 'postgres' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>

queue:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] || 'sta-postgres' %>
  port: <%= ENV['POSTGRES_PORT'] || 5432 %>
  database: <%= ENV['POSTGRES_DB'] || 'postgres' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>

cache:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] || 'sta-postgres' %>
  port: <%= ENV['POSTGRES_PORT'] || 5432 %>
  database: <%= ENV['POSTGRES_DB'] || 'postgres' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>
