default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: storage/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: storage/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRES_DB'] || 'postgres' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT'] || 5432 %>

  cable:
    <<: *default
    adapter: postgresql
    encoding: unicode
    database: <%= ENV['POSTGRES_DB'] || 'postgres' %>
    username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
    password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>
    host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
    port: <%= ENV['POSTGRES_PORT'] || 5432 %>
