# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[8.0].define(version: 2025_03_17_190026) do
  create_table "scholarship_applications", force: :cascade do |t|
    t.string "last_name"
    t.string "first_name"
    t.string "middle_initial"
    t.string "previous_maiden_name"
    t.string "student_id"
    t.date "date_of_birth"
    t.string "place_of_birth"
    t.string "marital_status"
    t.integer "number_of_dependents"
    t.string "tribe_enrolled"
    t.string "previous_scholarship"
    t.string "previous_scholarship_year"
    t.string "preferred_contact"
    t.string "email_address"
    t.string "mailing_address_permanent"
    t.string "city"
    t.string "state"
    t.string "zip_code"
    t.string "mailing_address_school"
    t.string "city_school"
    t.string "state_school"
    t.string "zip_code_school"
    t.string "permanent_phone"
    t.string "school_phone"
    t.string "school_name"
    t.string "school_city"
    t.string "school_earned_in"
    t.string "education_earned"
    t.string "college_name"
    t.string "college_financial_aid_office"
    t.string "college_phone"
    t.string "college_fax"
    t.string "college_financial_aid_mailing_address"
    t.string "college_city"
    t.string "college_state"
    t.string "college_zip_code"
    t.string "college_term_type"
    t.string "deadline_fee_payments"
    t.string "credits_taking"
    t.string "current_degree_program"
    t.date "expected_graduation_date"
    t.string "class_standing"
    t.string "field_of_study"
    t.string "minor"
    t.text "educational_goals"
    t.boolean "certify_information"
    t.string "signature"
    t.date "date"
    t.boolean "certify_not_defaulting"
    t.decimal "tuition"
    t.decimal "fees"
    t.decimal "room_board"
    t.decimal "books"
    t.decimal "transportation"
    t.decimal "personal_expenses"
    t.string "other_expenses"
    t.text "resources_college_expenses"
    t.decimal "amount_requested"
    t.string "release_signature"
    t.date "release_date"
    t.string "enrollment_last_name"
    t.string "enrollment_first_name"
    t.string "enrollment_middle_name"
    t.date "enrollment_date_of_birth"
    t.string "enrollment_sex"
    t.string "enrollment_phone"
    t.string "enrollment_place_of_birth"
    t.string "enrollment_mailing_city"
    t.string "enrollment_mailing_state"
    t.string "enrollment_mailing_zip"
    t.string "financial_student_name"
    t.string "financial_student_id"
    t.string "financial_aid_status"
    t.string "budget_period"
    t.text "student_resources"
    t.string "photo_release_signature"
    t.date "photo_release_date"
    t.string "parental_release_signature"
    t.date "parental_release_date"
    t.string "arpa_student_name"
    t.boolean "arpa_authorization"
    t.string "arpa_signature"
    t.date "arpa_date"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
end
